### PR TITLE
Remove casts to float in forward

### PR DESCRIPTION
**Pull request by gheinrich**

### CODE REVIEW

**Comment by mranzinger** [comment]
Did you verify this works with RADIOv2.1 and the clip adaptor head? e.g. does `python examples/zero_shot_imagenet.py --model-version radio_v2.1` still work?

**Comment by gheinrich** [comment]
Ah, indeed this isn't working anymore:

```
# PYTHONPATH=. python examples/zero_shot_imagenet.py --model-version radio_v2.1
Loading model...
No pretrained configuration specified for vit_huge_patch16_224 model. Using a default. Please add a config to the model pretrained_cfg registry or pass explicitly.
/lustre/fs12/portfolios/llmservice/users/gheinrich/RADIO/hubconf.py:69: UserWarning: Unexpected keys in state dict: ['head.weight', 'head.bias']
  warnings.warn(f'Unexpected keys in state dict: {key_warn.unexpected_keys}')
Done
Loading dataset...
Downloading builder script: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 4.58k/4.58k [00:00<00:00, 39.4MB/s]
Downloading readme: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 85.4k/85.4k [00:00<00:00, 1.06MB/s]
Downloading extra modules: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 46.4k/46.4k [00:00<00:00, 778kB/s]
Building Zero Shot Classifier...
batch: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 79/79 [01:02<00:00,  1.26it/s]
Done
Done
Description: ILSVRC 2012, commonly known as 'ImageNet' is an image dataset organized according to the WordNet hierarchy. Each meaningful concept in WordNet, possibly described by multiple words or word phrases, is called a "synonym set" or "synset". There are more than 100,000 synsets in WordNet, majority of them are nouns (80,000+). ImageNet aims to provide on average 1000 images to illustrate each synset. Images of each concept are quality-controlled and human-annotated. In its completion, ImageNet hopes to offer tens of millions of cleanly sorted images for most of the concepts in the WordNet hierarchy. ImageNet 2012 is the most commonly used subset of ImageNet. This dataset spans 1000 object classes and contains 1,281,167 training images, 50,000 validation images and 100,000 test images

Classifying at resolution=(432, 432)...
  0%|                                                                                                                                                                                                                                                   | 0/50000 [00:03<?, ?it/s]
[rank0]: Traceback (most recent call last):
[rank0]:   File "/lustre/fs12/portfolios/llmservice/users/gheinrich/RADIO/examples/zero_shot_imagenet.py", line 300, in <module>
[rank0]:     main(rank, world_size)
[rank0]:   File "/lustre/fs12/portfolios/llmservice/users/gheinrich/RADIO/examples/zero_shot_imagenet.py", line 152, in main
[rank0]:     output = model(images)
[rank0]:   File "/lustre/fsw/portfolios/llmservice/users/gheinrich/anaconda3/envs/vila/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
[rank0]:     return self._call_impl(*args, **kwargs)
[rank0]:   File "/lustre/fsw/portfolios/llmservice/users/gheinrich/anaconda3/envs/vila/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
[rank0]:     return forward_call(*args, **kwargs)
[rank0]:   File "/lustre/fs12/portfolios/llmservice/users/gheinrich/RADIO/radio/radio_model.py", line 164, in forward
[rank0]:     ret = self._extract_final(x, y, feature_fmt=feature_fmt)
[rank0]:   File "/lustre/fs12/portfolios/llmservice/users/gheinrich/RADIO/radio/radio_model.py", line 225, in _extract_final
[rank0]:     v = adaptor(ada_input).to(torch.float32)
[rank0]:   File "/lustre/fsw/portfolios/llmservice/users/gheinrich/anaconda3/envs/vila/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
[rank0]:     return self._call_impl(*args, **kwargs)
[rank0]:   File "/lustre/fsw/portfolios/llmservice/users/gheinrich/anaconda3/envs/vila/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
[rank0]:     return forward_call(*args, **kwargs)
[rank0]:   File "/lustre/fs12/portfolios/llmservice/users/gheinrich/RADIO/radio/adaptor_generic.py", line 45, in forward
[rank0]:     feat = self.feat_mlp(input.features)
[rank0]:   File "/lustre/fsw/portfolios/llmservice/users/gheinrich/anaconda3/envs/vila/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
[rank0]:     return self._call_impl(*args, **kwargs)
[rank0]:   File "/lustre/fsw/portfolios/llmservice/users/gheinrich/anaconda3/envs/vila/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
[rank0]:     return forward_call(*args, **kwargs)
[rank0]:   File "/lustre/fs12/portfolios/llmservice/users/gheinrich/RADIO/radio/adaptor_mlp.py", line 87, in forward
[rank0]:     x = self.fc1(x)
[rank0]:   File "/lustre/fsw/portfolios/llmservice/users/gheinrich/anaconda3/envs/vila/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
[rank0]:     return self._call_impl(*args, **kwargs)
[rank0]:   File "/lustre/fsw/portfolios/llmservice/users/gheinrich/anaconda3/envs/vila/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
[rank0]:     return forward_call(*args, **kwargs)
[rank0]:   File "/lustre/fsw/portfolios/llmservice/users/gheinrich/anaconda3/envs/vila/lib/python3.10/site-packages/torch/nn/modules/linear.py", line 116, in forward
[rank0]:     return F.linear(input, self.weight, self.bias)
[rank0]: RuntimeError: expected mat1 and mat2 to have the same dtype, but got: c10::BFloat16 != float

```

Would you like to propose a better fix?

**Comment by mranzinger** [comment]
Maybe have the adaptor do the explicit cast instead of the base model? Could even be something robust like this:

\<\<\<in adaptor_generic.py\>\>\>

```
def forward(input: AdaptorInput):
    first_prm = next(self.parameters())
    summary = self.head_mlp(input.summary.to(dtype=first_prm.dtype)).to(dtype=input.summary.dtype)
    feat = self.feat_mlp(input.features.to(dtype=first_prm.dtype).to(dtype=input.features.dtype)
    ...
```

**Comment by gheinrich** [comment]
Yes this is working now, thanks! I updated the PR.

**Review by mranzinger — APPROVED** [review]

**Pull request merged**
